name: Deploy new PHP83-Caddy Docker Image
on:
  workflow_dispatch:
jobs:
  build-image:
    name: Integrate last code on docker image and publish it on Ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Semver release
        id: release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
          git-user: 'mrkrash'
          git-user-email: 'mario@raval.li'

      - name: Metadata
        id: meta-data
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-php83-caddy
          tags: |
            type=raw,value=latest
            type=raw,value=prod
            type=raw,value=${{ steps.release.outputs.version }}
            type=sha,format=long

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./PHP83-Caddy/
          file: ./Dockerfile
          build-args: APP_ENV=prod
          target: prod
#          build-args: ARCH=${{ github.ref == format('refs/heads/{0}', 'main') && 'aarch64' || 'amd64' }}
#          platforms: ${{ github.ref == format('refs/heads/{0}', 'main') && 'linux/aarch64' || 'linux/amd64' }}
          tags: ${{ steps.meta-data.outputs.tags }}
          labels: ${{ steps.meta-data.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
